events {}

http {

upstream slims_backend {
    server slims-1:80;
    server slims-2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://slims_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

}
